NameError: global name 'localhost' is not defined

sqlalchemy.exc.OperationalError
OperationalError: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' (61)")

sqlalchemy.exc.OperationalError
OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: NO)")
